name: Ensure Code Quality
on: pull_request
jobs:
  build:
    name: Run linter and tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [22]
    steps:
      - name: Checkout Github repository.
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install Node.js dependencies.
        run: npm ci
      - name: Check ESLint into file(s).
        run: npm run lint
      - name: Compile TypeScript file(s).
        run: npm run build --if-present


